version: '3'

services:
  # --- CHATWOOT ---
  base: &base
    image: chatwoot/chatwoot:v3.3.1
    env_file: .env
    volumes:
      - ./storage:/app/storage

  rails:
    <<: *base
    depends_on:
      - postgres
      - redis
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
      - POSTGRES_HOST=postgres
      - POSTGRES_USERNAME=chatwoot
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    entrypoint: docker/entrypoints/rails.sh
    command: [ 'bundle', 'exec', 'rails', 's', '-p', '3000', '-b', '0.0.0.0' ]

  sidekiq:
    <<: *base
    depends_on:
      - postgres
      - redis
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - POSTGRES_HOST=postgres
      - POSTGRES_USERNAME=chatwoot
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    command: [ 'bundle', 'exec', 'sidekiq', '-C', 'config/sidekiq.yml' ]

  # --- INFRASTRUCTURE ---
  postgres:
    image: postgres:15-alpine
    restart: always
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=chatwoot_production
      - POSTGRES_USER=chatwoot
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  redis:
    image: redis:6.2-alpine
    restart: always
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}" ]
    volumes:
      - ./redis_data:/data

  # --- EVOLUTION API v2 ---
  evolution:
    image: evoapicloud/evolution-api:v2.3.0
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./evolution_instances:/evolution/instances
      - ./evolution_store:/evolution/store
    environment:
      - DOCKER_ENV=true
      # --- Database ---
      - DATABASE_ENABLED=true
      - DATABASE_PROVIDER=postgresql
      - DATABASE_CONNECTION_URI=postgresql://chatwoot:${POSTGRES_PASSWORD}@postgres:5432/evolution?schema=public&sslmode=disable
      - DATABASE_SAVE_DATA_INSTANCE=true
      - DATABASE_SAVE_DATA_NEW_MESSAGE=true
      - DATABASE_SAVE_MESSAGE_UPDATE=true
      - DATABASE_SAVE_DATA_CONTACTS=true
      - DATABASE_SAVE_DATA_CHATS=true
      - DATABASE_SAVE_DATA_HISTORIC=true
      # --- Auth ---
      - AUTHENTICATION_API_KEY=mypassy
      # --- Cache ---
      - CACHE_REDIS_ENABLED=true
      - CACHE_REDIS_URI=redis://:${REDIS_PASSWORD}@redis:6379/1
      - CACHE_REDIS_PREFIX=evo
      # --- Chatwoot Integration ---
      - CHATWOOT_ENABLED=true
      - CHATWOOT_URL=http://rails:3000
      - CHATWOOT_TOKEN=pgh3rRR6ZLirSnzdnuQZbhNV
      - CHATWOOT_ACCOUNT_ID=1
      - CHATWOOT_SIGN_MSG=false
      - CHATWOOT_REOPEN_CONVERSATION=true
      - CHATWOOT_CONVERSATION_PENDING=false
      - CHATWOOT_IMPORT_DATABASE_CONNECTION_URI=postgresql://chatwoot:${POSTGRES_PASSWORD}@postgres:5432/chatwoot_production
      - CHATWOOT_IMPORT_PLACEHOLDER_MEDIA_MESSAGE=true
